"""
Smart Road Pothole Detection System — Streamlit UI
==================================================
BMCS2003 Artificial Intelligence Assignment (Title 6: Image Processing & CV)

Models: YOLOv8n | SSD300-VGG16 | Faster R-CNN ResNet50-FPN

Design system (generated by ui-ux-pro-max):
  Style      : Zero Interface (AI / ambient, dark-first)
  Palette    : #0F172A bg, #1E293B primary, #22C55E accent, #EF4444 destructive
  Typography : Fira Code (headings/metrics) + Fira Sans (body)
  Motion     : stagger reveal, counter animation, back.out(1.4) easing

Run:  streamlit run ui.py
"""

from __future__ import annotations

import io
import os
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np
import pandas as pd
import streamlit as st

# ----------------------------------------------------------------------
# PAGE CONFIG — must be the first Streamlit call
# ----------------------------------------------------------------------
st.set_page_config(
    page_title="Smart Road Pothole Detection",
    page_icon="◉",
    layout="wide",
    initial_sidebar_state="expanded",
)

MODELS_DIR = Path(os.environ.get("POTHOLE_MODELS_DIR", "models"))

MODEL_FILES = {
    "YOLOv8n": MODELS_DIR / "best_pothole_yolov8n.pt",
    "SSD300-VGG16": MODELS_DIR / "best_ssd300_vgg16_pothole.pth",
    "Faster R-CNN ResNet50-FPN": MODELS_DIR / "best_faster_rcnn_pothole.pth",
}

MODEL_NAMES = list(MODEL_FILES)

# Test-set results (from the team's final evaluation notebooks)
BENCHMARK = {
    "YOLOv8n": {
        "mAP@0.5": 0.914, "mAP@0.5:0.95": 0.621, "Precision": 0.891,
        "Recall": 0.815, "F1": 0.852, "FPS": 120.0, "Params (M)": 3.0,
    },
    "SSD300-VGG16": {
        "mAP@0.5": 0.808, "mAP@0.5:0.95": 0.488, "Precision": 0.880,
        "Recall": 0.674, "F1": 0.763, "FPS": 49.0, "Params (M)": 23.7,
    },
    "Faster R-CNN ResNet50-FPN": {
        "mAP@0.5": 0.885, "mAP@0.5:0.95": 0.510, "Precision": 0.697,
        "Recall": 0.898, "F1": 0.785, "FPS": 15.4, "Params (M)": 41.3,
    },
}

# Severity colours (RGB) — green / amber / red
SEVERITY_RGB = {
    "small": (34, 197, 94),
    "medium": (245, 158, 11),
    "large": (239, 68, 68),
}
SEVERITY_HEX = {"small": "#22C55E", "medium": "#F59E0B", "large": "#EF4444"}
SEVERITY_RANK = {"small": 0, "medium": 1, "large": 2}


# ======================================================================
# DESIGN SYSTEM — CSS
# ======================================================================
def inject_design_system() -> None:
    st.markdown(
        """
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600;700&family=Fira+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
:root {
  --color-primary:      #1E293B;
  --color-on-primary:   #FFFFFF;
  --color-secondary:    #334155;
  --color-accent:       #22C55E;
  --color-background:   #0F172A;
  --color-foreground:   #F8FAFC;
  --color-muted:        #272F42;
  --color-border:       #475569;
  --color-destructive:  #EF4444;
  --color-warning:      #F59E0B;
  --radius-sm: 8px;
  --radius-md: 14px;
  --radius-lg: 20px;
  --shadow-1: 0 1px 3px rgba(0,0,0,.35);
  --shadow-2: 0 8px 24px rgba(0,0,0,.45);
  --ease-out-back: cubic-bezier(.34,1.56,.64,1);
}

html, body, [class*="css"], .stApp {
  background: var(--color-background);
  color: var(--color-foreground);
  font-family: 'Fira Sans', system-ui, sans-serif;
  font-display: swap;
}

h1, h2, h3, h4, .metric-value, .mono {
  font-family: 'Fira Code', ui-monospace, monospace;
  letter-spacing: -.02em;
}

/* ---------- ambient background (Zero Interface style) ---------- */
.stApp::before {
  content: "";
  position: fixed;
  inset: 0;
  background:
    radial-gradient(60rem 60rem at 12% -10%, rgba(34,197,94,.10), transparent 60%),
    radial-gradient(50rem 50rem at 110% 10%, rgba(59,130,246,.10), transparent 60%);
  pointer-events: none;
  z-index: 0;
}
.block-container { position: relative; z-index: 1; padding-top: 2rem; }

/* ---------- hero ---------- */
.hero {
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: 2rem 2.25rem;
  background:
    linear-gradient(135deg, rgba(30,41,59,.92), rgba(15,23,42,.92));
  box-shadow: var(--shadow-2);
  animation: rise .5s var(--ease-out-back) both;
  overflow: hidden;
  position: relative;
}
.hero::after {
  content: "";
  position: absolute;
  left: -30%; bottom: -1px;
  width: 160%; height: 2px;
  background: linear-gradient(90deg, transparent, var(--color-accent), transparent);
  animation: scan 3.2s linear infinite;
}
.hero h1 { margin: 0 0 .4rem 0; font-size: clamp(1.5rem, 3.2vw, 2.3rem); font-weight: 700; }
.hero p  { margin: 0; color: #CBD5E1; font-size: 1rem; line-height: 1.6; max-width: 68ch; }

.badge {
  display: inline-flex; align-items: center; gap: .45rem;
  padding: .3rem .7rem; margin-bottom: .9rem;
  border-radius: 999px;
  background: rgba(34,197,94,.12);
  border: 1px solid rgba(34,197,94,.42);
  color: var(--color-accent);
  font-family: 'Fira Code', monospace; font-size: .74rem; font-weight: 600;
  letter-spacing: .06em; text-transform: uppercase;
}
.badge .dot {
  width: 7px; height: 7px; border-radius: 50%;
  background: var(--color-accent);
  animation: pulse 1.9s ease-in-out infinite;
}

/* ---------- metric cards ---------- */
.card {
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: rgba(39,47,66,.55);
  padding: 1.05rem 1.15rem;
  box-shadow: var(--shadow-1);
  transition: transform .22s ease, border-color .22s ease, box-shadow .22s ease;
  animation: rise .45s var(--ease-out-back) both;
  height: 100%;
}
.card:hover {
  transform: translateY(-3px);
  border-color: var(--color-accent);
  box-shadow: var(--shadow-2);
}
.card .label {
  font-size: .72rem; letter-spacing: .09em; text-transform: uppercase;
  color: #94A3B8; font-weight: 600; margin-bottom: .35rem;
}
.card .metric-value { font-size: 1.75rem; font-weight: 700; line-height: 1.1; }
.card .sub { font-size: .78rem; color: #94A3B8; margin-top: .2rem; }

/* stagger children */
.s1 { animation-delay: .04s; }
.s2 { animation-delay: .10s; }
.s3 { animation-delay: .16s; }
.s4 { animation-delay: .22s; }

/* ---------- warning banner ---------- */
.alert {
  border-radius: var(--radius-md);
  padding: .95rem 1.15rem;
  font-weight: 600;
  display: flex; align-items: center; gap: .7rem;
  animation: rise .4s var(--ease-out-back) both;
}
.alert-danger {
  background: rgba(239,68,68,.13);
  border: 1px solid rgba(239,68,68,.55);
  color: #FCA5A5;
}
.alert-ok {
  background: rgba(34,197,94,.10);
  border: 1px solid rgba(34,197,94,.42);
  color: #86EFAC;
}
.alert-danger .icon { animation: pulse 1.4s ease-in-out infinite; }

/* ---------- winner pill ---------- */
.pill {
  display: inline-block; padding: .18rem .6rem; border-radius: 999px;
  font-family: 'Fira Code', monospace; font-size: .72rem; font-weight: 600;
}
.pill-best { background: rgba(34,197,94,.15); color: #86EFAC; border: 1px solid rgba(34,197,94,.5); }

/* ---------- streamlit overrides ---------- */
.stButton > button {
  width: 100%;
  border-radius: var(--radius-sm);
  border: 1px solid var(--color-accent);
  background: linear-gradient(135deg, #16A34A, #22C55E);
  color: #04240F;
  font-family: 'Fira Code', monospace;
  font-weight: 700;
  letter-spacing: .03em;
  padding: .62rem 1rem;   /* keeps target >= 44px tall */
  min-height: 44px;
  cursor: pointer;
  transition: transform .18s ease, box-shadow .18s ease, filter .18s ease;
}
.stButton > button:hover { transform: translateY(-2px); box-shadow: 0 8px 20px rgba(34,197,94,.32); filter: brightness(1.05); }
.stButton > button:active { transform: translateY(0); }
.stButton > button:focus-visible { outline: 3px solid #7DD3FC; outline-offset: 2px; }

.stTabs [data-baseweb="tab-list"] { gap: .4rem; border-bottom: 1px solid var(--color-border); }
.stTabs [data-baseweb="tab"] {
  font-family: 'Fira Code', monospace; font-size: .86rem; font-weight: 600;
  border-radius: var(--radius-sm) var(--radius-sm) 0 0;
  padding: .55rem 1.05rem; min-height: 44px; cursor: pointer;
  transition: background .2s ease, color .2s ease;
}
.stTabs [aria-selected="true"] { background: rgba(34,197,94,.12); color: var(--color-accent) !important; }

section[data-testid="stSidebar"] {
  background: linear-gradient(180deg, #111C31, #0B1220);
  border-right: 1px solid var(--color-border);
}
[data-testid="stFileUploaderDropzone"] {
  border: 1.5px dashed var(--color-border);
  border-radius: var(--radius-md);
  background: rgba(39,47,66,.4);
  transition: border-color .2s ease, background .2s ease;
}
[data-testid="stFileUploaderDropzone"]:hover {
  border-color: var(--color-accent);
  background: rgba(34,197,94,.06);
}
[data-testid="stDataFrame"] { border-radius: var(--radius-md); overflow: hidden; }

/* ---------- keyframes ---------- */
@keyframes rise  { from { opacity: 0; transform: translateY(14px) scale(.97); } to { opacity: 1; transform: none; } }
@keyframes pulse { 0%,100% { opacity: 1; transform: scale(1); } 50% { opacity: .45; transform: scale(.86); } }
@keyframes scan  { 0% { transform: translateX(-30%); } 100% { transform: translateX(30%); } }

/* ---------- accessibility: honour reduced motion ---------- */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: .001ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: .001ms !important;
  }
}

/* ---------- responsive ---------- */
@media (max-width: 768px) {
  .hero { padding: 1.35rem 1.25rem; }
  .card .metric-value { font-size: 1.4rem; }
  body { font-size: 16px; }   /* prevents iOS auto-zoom */
}
</style>
        """,
        unsafe_allow_html=True,
    )


def svg_icon(path_d: str, colour: str = "#22C55E", size: int = 18) -> str:
    """Inline SVG icon (never emoji-as-icon)."""
    return (
        f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" '
        f'stroke="{colour}" stroke-width="2" stroke-linecap="round" '
        f'stroke-linejoin="round" aria-hidden="true">{path_d}</svg>'
    )


ICON_ALERT = '<path d="M12 9v4M12 17h.01M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>'
ICON_CHECK = '<path d="M20 6 9 17l-5-5"/>'


# ======================================================================
# MODEL LOADING (cached)
# ======================================================================
@st.cache_resource(show_spinner=False)
def get_device():
    import torch
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


@st.cache_resource(show_spinner=False)
def load_model(model_name: str):
    """Load and cache one detector. Raises FileNotFoundError with a clear message."""
    import torch
    from torchvision.models.detection import (
        fasterrcnn_resnet50_fpn,
        ssd300_vgg16,
    )

    path = MODEL_FILES[model_name]
    if not path.is_file():
        raise FileNotFoundError(
            f"Checkpoint for {model_name} not found at: {path}\n"
            f"Place the file there, or set POTHOLE_MODELS_DIR."
        )

    device = get_device()

    if model_name == "YOLOv8n":
        from ultralytics import YOLO
        return YOLO(str(path))

    if model_name == "SSD300-VGG16":
        model = ssd300_vgg16(weights=None, weights_backbone=None, num_classes=2)
    else:
        # min_size = max_size = 640 matches the training configuration exactly
        model = fasterrcnn_resnet50_fpn(
            weights=None, weights_backbone=None, num_classes=2,
            min_size=640, max_size=640,
        )

    checkpoint = torch.load(str(path), map_location="cpu", weights_only=False)
    state = checkpoint
    if isinstance(checkpoint, dict):
        for key in ("model_state_dict", "state_dict", "model"):
            value = checkpoint.get(key)
            if isinstance(value, dict):
                state = value
                break
            if hasattr(value, "state_dict"):
                state = value.state_dict()
                break
    if all(k.startswith("module.") for k in state):
        state = {k[7:]: v for k, v in state.items()}

    model.load_state_dict(state, strict=True)
    model.to(device).eval()
    return model


def checkpoint_status() -> Dict[str, bool]:
    return {name: path.is_file() for name, path in MODEL_FILES.items()}


# ======================================================================
# INFERENCE
# ======================================================================
def ensure_rgb(image: np.ndarray) -> np.ndarray:
    array = np.asarray(image)
    if array.ndim == 2:
        array = cv2.cvtColor(array, cv2.COLOR_GRAY2RGB)
    elif array.shape[-1] == 4:
        array = cv2.cvtColor(array, cv2.COLOR_RGBA2RGB)
    if array.dtype != np.uint8:
        array = np.clip(array, 0, 255).astype(np.uint8)
    return np.ascontiguousarray(array)


def run_inference(
    image_rgb: np.ndarray,
    model_name: str,
    confidence: float,
) -> Tuple[List[Dict[str, Any]], float]:
    """Returns (detections, latency_ms). Timer covers the same work for all models."""
    import torch

    model = load_model(model_name)
    device = get_device()
    detections: List[Dict[str, Any]] = []

    if model_name == "YOLOv8n":
        # Ultralytics expects BGR for numpy input
        image_bgr = np.ascontiguousarray(image_rgb[:, :, ::-1])
        if device.type == "cuda":
            torch.cuda.synchronize()
        start = time.perf_counter()
        result = model.predict(
            source=image_bgr, conf=float(confidence), iou=0.45,
            imgsz=640, verbose=False,
        )[0]
        if device.type == "cuda":
            torch.cuda.synchronize()
        latency_ms = (time.perf_counter() - start) * 1000

        if result.boxes is not None and len(result.boxes):
            for box, score in zip(
                result.boxes.xyxy.cpu().numpy(),
                result.boxes.conf.cpu().numpy(),
            ):
                detections.append(
                    {"box": [float(v) for v in box], "score": float(score)}
                )
        return detections, latency_ms

    from torchvision.transforms.functional import to_tensor

    if device.type == "cuda":
        torch.cuda.synchronize()
    start = time.perf_counter()
    tensor = to_tensor(image_rgb).to(device)
    with torch.inference_mode():
        output = model([tensor])[0]
    if device.type == "cuda":
        torch.cuda.synchronize()
    latency_ms = (time.perf_counter() - start) * 1000

    boxes = output["boxes"].cpu().numpy()
    scores = output["scores"].cpu().numpy()
    labels = output["labels"].cpu().numpy()
    for box, score, label in zip(boxes, scores, labels):
        if float(score) >= float(confidence) and int(label) == 1:
            detections.append(
                {"box": [float(v) for v in box], "score": float(score)}
            )
    return detections, latency_ms


def enrich(
    detection: Dict[str, Any],
    shape: Tuple[int, int, int],
    pixels_per_cm: float,
    large_percent: float,
    large_cm2: float,
) -> Dict[str, Any]:
    """Adds size measurements and a severity tier to one detection."""
    height, width = shape[:2]
    x1, y1, x2, y2 = detection["box"]
    x1 = max(0.0, min(width - 1.0, x1))
    y1 = max(0.0, min(height - 1.0, y1))
    x2 = max(0.0, min(float(width), x2))
    y2 = max(0.0, min(float(height), y2))

    box_w, box_h = max(0.0, x2 - x1), max(0.0, y2 - y1)
    area_percent = 100.0 * (box_w * box_h) / max(1.0, width * height)

    ppc = float(pixels_per_cm or 0.0)
    calibrated = ppc > 0
    width_cm = box_w / ppc if calibrated else None
    height_cm = box_h / ppc if calibrated else None
    area_cm2 = (width_cm * height_cm) if calibrated else None

    threshold = float(large_cm2) if calibrated else float(large_percent)
    measure = area_cm2 if calibrated else area_percent
    if measure >= threshold:
        severity = "large"
    elif measure >= threshold / 2:
        severity = "medium"
    else:
        severity = "small"

    out = dict(detection)
    out.update({
        "box": [x1, y1, x2, y2],
        "box_width_px": box_w, "box_height_px": box_h,
        "area_percent": area_percent, "calibrated": calibrated,
        "width_cm": width_cm, "height_cm": height_cm, "area_cm2": area_cm2,
        "severity": severity, "is_large": severity == "large",
    })
    return out


def draw_label(canvas, text, x, y, rgb):
    font = cv2.FONT_HERSHEY_SIMPLEX
    (tw, th), base = cv2.getTextSize(text, font, 0.52, 1)
    x = max(0, min(canvas.shape[1] - tw - 10, int(x)))
    y = max(th + base + 8, int(y))
    cv2.rectangle(canvas, (x, y - th - base - 7), (x + tw + 10, y + 1), rgb, -1)
    cv2.putText(canvas, text, (x + 5, y - base - 1), font, 0.52,
                (255, 255, 255), 1, cv2.LINE_AA)


def annotate(
    image_rgb: np.ndarray,
    detections: List[Dict[str, Any]],
    model_name: str,
    latency_ms: float,
) -> np.ndarray:
    canvas = image_rgb.copy()
    height, width = canvas.shape[:2]

    for index, det in enumerate(detections, start=1):
        x1, y1, x2, y2 = [int(round(v)) for v in det["box"]]
        rgb = SEVERITY_RGB[det["severity"]]
        cv2.rectangle(canvas, (x1, y1), (x2, y2), rgb,
                      4 if det["is_large"] else 2)
        if det["calibrated"]:
            size_text = f"{det['width_cm']:.0f}x{det['height_cm']:.0f}cm"
        else:
            size_text = f"{det['area_percent']:.1f}%"
        draw_label(canvas, f"#{index} {det['score']:.2f} | {size_text} | "
                           f"{det['severity'].upper()}", x1, max(24, y1), rgb)

    draw_label(canvas, f"{model_name} | {len(detections)} pothole(s) | "
                       f"{latency_ms:.1f} ms", 8, height - 10, (30, 41, 59))

    large = sum(d["is_large"] for d in detections)
    if large:
        bar = max(40, int(height * .07))
        overlay = canvas.copy()
        cv2.rectangle(overlay, (0, 0), (width, bar), SEVERITY_RGB["large"], -1)
        cv2.addWeighted(overlay, .85, canvas, .15, 0, canvas)
        cv2.putText(canvas, f"WARNING: {large} LARGE POTHOLE(S)",
                    (14, int(bar * .68)), cv2.FONT_HERSHEY_SIMPLEX,
                    max(.6, min(1.05, width / 950)), (255, 255, 255), 2,
                    cv2.LINE_AA)
    return canvas


def rows_from(detections, model_name, latency_ms) -> List[Dict[str, Any]]:
    rows = []
    for index, det in enumerate(detections, start=1):
        x1, y1, x2, y2 = det["box"]
        rows.append({
            "Model": model_name,
            "No.": index,
            "Confidence": round(det["score"], 4),
            "X1": round(x1, 1), "Y1": round(y1, 1),
            "X2": round(x2, 1), "Y2": round(y2, 1),
            "Width (px)": round(det["box_width_px"], 1),
            "Height (px)": round(det["box_height_px"], 1),
            "Area (% frame)": round(det["area_percent"], 3),
            "Width (cm)": None if det["width_cm"] is None else round(det["width_cm"], 1),
            "Height (cm)": None if det["height_cm"] is None else round(det["height_cm"], 1),
            "Area (cm2)": None if det["area_cm2"] is None else round(det["area_cm2"], 1),
            "Severity": det["severity"].capitalize(),
            "Large": "YES" if det["is_large"] else "No",
            "Latency (ms)": round(latency_ms, 2),
        })
    return rows


# ======================================================================
# UI COMPONENTS
# ======================================================================
def metric_card(label: str, value: str, sub: str = "", colour: str | None = None,
                stagger: int = 1) -> str:
    tint = f"color:{colour};" if colour else ""
    return (
        f'<div class="card s{stagger}">'
        f'<div class="label">{label}</div>'
        f'<div class="metric-value" style="{tint}">{value}</div>'
        f'<div class="sub">{sub}</div>'
        f"</div>"
    )


def hero() -> None:
    st.markdown(
        '<div class="hero">'
        '<span class="badge"><span class="dot"></span>Computer Vision · Live</span>'
        "<h1>Smart Road Pothole Detection</h1>"
        "<p>Detect and measure road potholes using three deep-learning detectors — "
        "YOLOv8n, SSD300-VGG16 and Faster R-CNN. Upload a road image or video to "
        "see bounding boxes, severity tiers and per-model inference speed.</p>"
        "</div>",
        unsafe_allow_html=True,
    )


def severity_legend() -> None:
    st.markdown(
        '<div style="display:flex;gap:1.2rem;flex-wrap:wrap;margin:.9rem 0 .2rem 0;'
        'font-size:.82rem;color:#94A3B8;">'
        + "".join(
            f'<span><span style="display:inline-block;width:11px;height:11px;'
            f'border-radius:3px;background:{SEVERITY_HEX[key]};margin-right:.4rem;'
            f'vertical-align:middle;"></span>{key.capitalize()}</span>'
            for key in ("small", "medium", "large")
        )
        + "</div>",
        unsafe_allow_html=True,
    )


# ======================================================================
# SIDEBAR
# ======================================================================
def sidebar() -> Dict[str, Any]:
    with st.sidebar:
        st.markdown("### Detection settings")

        status = checkpoint_status()
        ready = [n for n, ok in status.items() if ok]
        for name, ok in status.items():
            icon = svg_icon(ICON_CHECK, "#22C55E") if ok else svg_icon(ICON_ALERT, "#EF4444")
            colour = "#86EFAC" if ok else "#FCA5A5"
            label = "loaded" if ok else "missing"
            st.markdown(
                f'<div style="display:flex;align-items:center;gap:.5rem;'
                f'padding:.3rem 0;font-size:.84rem;color:{colour};">{icon}'
                f"<span>{name} — {label}</span></div>",
                unsafe_allow_html=True,
            )

        if not ready:
            st.error(
                f"No checkpoints found in `{MODELS_DIR}/`. "
                "Add the .pt/.pth files to run detection."
            )

        st.divider()

        options = (["Compare all models"] + ready) if len(ready) > 1 else ready
        model_choice = st.selectbox(
            "Model", options or ["(no model available)"],
            help="Compare mode runs every available model on the same input.",
        )
        confidence = st.slider(
            "Confidence threshold", 0.05, 0.95, 0.50, 0.05,
            help="Detections below this score are discarded.",
        )

        st.divider()
        st.markdown("### Size estimation")
        pixels_per_cm = st.number_input(
            "Pixels per cm (0 = relative mode)", min_value=0.0, value=0.0, step=0.5,
            help="Measure a known object (A4 long side = 29.7 cm) in pixels, "
                 "then divide by its real length.",
        )
        large_percent = st.slider(
            "Large threshold — % of frame", 0.1, 30.0, 5.0, 0.1,
            help="Medium starts at half this value.",
        )
        large_cm2 = st.number_input(
            "Large threshold — area (cm²)", min_value=1.0, value=2500.0, step=100.0,
        )

        with st.expander("How size is measured"):
            st.markdown(
                "Detectors output a **rectangular box**, so measurements estimate "
                "the box — not the true irregular pothole outline.\n\n"
                "- **Relative mode:** box area as a % of the frame.\n"
                "- **Calibrated mode:** `cm = pixels ÷ (pixels per cm)`.\n\n"
                "A single pixels-per-cm value is only valid at one camera "
                "distance and angle. Accurate area needs segmentation."
            )

    return {
        "model_choice": model_choice,
        "ready": ready,
        "confidence": confidence,
        "pixels_per_cm": pixels_per_cm,
        "large_percent": large_percent,
        "large_cm2": large_cm2,
    }


# ======================================================================
# TAB 1 — IMAGE
# ======================================================================
def tab_image(cfg: Dict[str, Any]) -> None:
    upload = st.file_uploader(
        "Upload a road image", type=["jpg", "jpeg", "png", "bmp", "webp"],
        key="image_upload",
    )
    if upload is None:
        st.info("Upload a road image to start detection.")
        return

    from PIL import Image
    image_rgb = ensure_rgb(np.array(Image.open(io.BytesIO(upload.getvalue()))))

    left, right = st.columns([1, 1], gap="large")
    with left:
        st.markdown("**Input**")
        st.image(image_rgb, use_container_width=True)

    if not st.button("Detect potholes", key="detect_image"):
        return
    if not cfg["ready"]:
        st.error("No model checkpoints available.")
        return

    targets = cfg["ready"] if cfg["model_choice"] == "Compare all models" else [cfg["model_choice"]]
    all_rows: List[Dict[str, Any]] = []
    results = []

    progress = st.progress(0.0, text="Preparing models…")
    for index, name in enumerate(targets, start=1):
        progress.progress((index - 1) / len(targets), text=f"Running {name}…")
        try:
            detections, latency = run_inference(image_rgb, name, cfg["confidence"])
        except Exception as error:              # noqa: BLE001
            st.error(f"{name} failed: {error}")
            continue
        enriched = [
            enrich(d, image_rgb.shape, cfg["pixels_per_cm"],
                   cfg["large_percent"], cfg["large_cm2"])
            for d in detections
        ]
        results.append((name, enriched, latency, annotate(image_rgb, enriched, name, latency)))
        all_rows.extend(rows_from(enriched, name, latency))
    progress.progress(1.0, text="Done")
    progress.empty()

    if not results:
        return

    with right:
        st.markdown("**Detection result**")
        tabs = st.tabs([n for n, _, _, _ in results])
        for tab, (name, enriched, latency, annotated) in zip(tabs, results):
            with tab:
                st.image(annotated, use_container_width=True)
    severity_legend()

    # summary cards for the first (or selected) model
    name, enriched, latency, _ = results[0]
    large = sum(d["is_large"] for d in enriched)
    top = max((d["score"] for d in enriched), default=0.0)

    cols = st.columns(4)
    cards = [
        ("Potholes found", str(len(enriched)), name, None),
        ("Large warnings", str(large), "severity tier",
         SEVERITY_HEX["large"] if large else None),
        ("Top confidence", f"{top * 100:.1f}%", "highest scoring box", None),
        ("Latency", f"{latency:.1f} ms", f"{1000 / max(latency, .01):.0f} FPS", None),
    ]
    for col, (label, value, sub, colour), step in zip(cols, cards, range(1, 5)):
        col.markdown(metric_card(label, value, sub, colour, step), unsafe_allow_html=True)

    if large:
        st.markdown(
            f'<div class="alert alert-danger" style="margin-top:1rem;">'
            f'<span class="icon">{svg_icon(ICON_ALERT, "#FCA5A5", 20)}</span>'
            f"<span>{large} large pothole(s) detected — immediate repair "
            f"recommended.</span></div>",
            unsafe_allow_html=True,
        )
    elif enriched:
        st.markdown(
            f'<div class="alert alert-ok" style="margin-top:1rem;">'
            f'{svg_icon(ICON_CHECK, "#86EFAC", 20)}'
            f"<span>No large potholes detected at the current threshold.</span></div>",
            unsafe_allow_html=True,
        )

    if all_rows:
        st.markdown("#### Detection details")
        frame = pd.DataFrame(all_rows)
        st.dataframe(frame, use_container_width=True, hide_index=True)
        st.download_button(
            "Download detections (CSV)",
            frame.to_csv(index=False).encode("utf-8"),
            file_name=f"pothole_detections_{uuid.uuid4().hex[:8]}.csv",
            mime="text/csv",
        )

    if len(results) > 1:
        st.caption(
            "Detections on a single image are qualitative. Model ranking comes "
            "from the labelled test set — see the Benchmark tab."
        )


# ======================================================================
# TAB 2 — VIDEO
# ======================================================================
def tab_video(cfg: Dict[str, Any]) -> None:
    upload = st.file_uploader(
        "Upload a road video", type=["mp4", "mov", "avi", "mkv"], key="video_upload"
    )

    controls = st.columns(3)
    stride = controls[0].slider("Analyse every Nth frame", 1, 10, 2)
    max_seconds = controls[1].number_input("Max seconds (0 = full)", 0.0, 600.0, 15.0, 5.0)
    line_fraction = controls[2].slider("Counting line (frame height)", 0.30, 0.90, 0.65, 0.05)

    if upload is None:
        st.info("Upload a road video to start analysis.")
        return
    if not st.button("Process video", key="detect_video"):
        return
    if not cfg["ready"]:
        st.error("No model checkpoints available.")
        return

    model_name = (cfg["ready"][0] if cfg["model_choice"] == "Compare all models"
                  else cfg["model_choice"])

    temp_dir = Path("temp_uploads")
    temp_dir.mkdir(exist_ok=True)
    input_path = temp_dir / f"in_{uuid.uuid4().hex[:8]}.mp4"
    input_path.write_bytes(upload.getvalue())

    capture = cv2.VideoCapture(str(input_path))
    if not capture.isOpened():
        st.error("Could not open the uploaded video.")
        return

    fps = capture.get(cv2.CAP_PROP_FPS) or 25.0
    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
    limit = int(max_seconds * fps) if max_seconds > 0 else total
    limit = min(limit, total) if total > 0 else limit
    line_y = int(height * line_fraction)

    output_path = temp_dir / f"out_{uuid.uuid4().hex[:8]}.mp4"
    writer = cv2.VideoWriter(str(output_path), cv2.VideoWriter_fourcc(*"mp4v"),
                             fps, (width, height))

    tracks: Dict[int, Dict[str, Any]] = {}
    next_id = 1
    unique_total = unique_large = 0
    counted: List[Tuple[int, float, str]] = []
    rows: List[Dict[str, Any]] = []
    last: List[Dict[str, Any]] = []
    last_ids: List[int] = []
    last_latency = 0.0
    first_time: Optional[float] = None

    progress = st.progress(0.0, text="Starting…")
    preview = st.empty()
    frame_index = 0

    def iou(a, b) -> float:
        ax1, ay1, ax2, ay2 = a
        bx1, by1, bx2, by2 = b
        ix1, iy1 = max(ax1, bx1), max(ay1, by1)
        ix2, iy2 = min(ax2, bx2), min(ay2, by2)
        inter = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
        union = (ax2 - ax1) * (ay2 - ay1) + (bx2 - bx1) * (by2 - by1) - inter
        return inter / union if union > 0 else 0.0

    while frame_index < limit:
        ok, frame_bgr = capture.read()
        if not ok:
            break
        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        seconds = frame_index / fps

        if frame_index % stride == 0:
            try:
                detections, last_latency = run_inference(
                    frame_rgb, model_name, cfg["confidence"]
                )
            except Exception as error:          # noqa: BLE001
                st.error(f"{model_name} failed: {error}")
                break
            last = [
                enrich(d, frame_rgb.shape, cfg["pixels_per_cm"],
                       cfg["large_percent"], cfg["large_cm2"])
                for d in detections
            ]

            # --- greedy IoU tracking ---
            assigned: List[Optional[int]] = [None] * len(last)
            pairs = sorted(
                ((iou(t["box"], d["box"]), tid, i)
                 for tid, t in tracks.items() for i, d in enumerate(last)
                 if iou(t["box"], d["box"]) >= 0.3),
                reverse=True,
            )
            used_t, used_d = set(), set()
            for _, tid, i in pairs:
                if tid in used_t or i in used_d:
                    continue
                assigned[i] = tid
                used_t.add(tid)
                used_d.add(i)
            for i, det in enumerate(last):
                if assigned[i] is None:
                    assigned[i] = next_id
                    centre = 0.5 * (det["box"][1] + det["box"][3])
                    tracks[next_id] = {
                        "box": det["box"], "age": 0, "last_cy": centre,
                        "counted": False, "born_below": centre > line_y,
                        "rank": SEVERITY_RANK[det["severity"]],
                    }
                    next_id += 1
                    continue
                tid = assigned[i]
                track = tracks[tid]
                centre = 0.5 * (det["box"][1] + det["box"][3])
                track["age"] += 1
                track["box"] = det["box"]
                track["rank"] = max(track["rank"], SEVERITY_RANK[det["severity"]])
                crossed = track["last_cy"] <= line_y < centre
                if (not track["counted"] and not track["born_below"]
                        and track["age"] >= 3 and crossed):
                    track["counted"] = True
                    unique_total += 1
                    tier = "Large" if track["rank"] >= 2 else "Small/Medium"
                    if track["rank"] >= 2:
                        unique_large += 1
                    counted.append((tid, seconds, tier))
                track["last_cy"] = centre
            last_ids = [int(a) for a in assigned]

            if last and first_time is None:
                first_time = seconds
            for row in rows_from(last, model_name, last_latency):
                row["Time (s)"] = round(seconds, 2)
                row["Frame"] = frame_index
                rows.append(row)

        annotated = annotate(frame_rgb, last, model_name, last_latency)
        cv2.line(annotated, (0, line_y), (width, line_y), (56, 189, 248), 2)
        for det, tid in zip(last, last_ids):
            mark = " ✓" if tracks.get(tid, {}).get("counted") else ""
            draw_label(annotated, f"ID {tid}{mark}", det["box"][0],
                       min(height - 4, det["box"][3] + 20), (30, 41, 59))
        draw_label(annotated,
                   f"In frame {len(last)} | Unique {unique_total} | Large {unique_large}",
                   8, 26, (30, 41, 59))
        draw_label(annotated, f"t={seconds:05.1f}s", 8, height - 44, (30, 41, 59))

        writer.write(cv2.cvtColor(annotated, cv2.COLOR_RGB2BGR))

        if frame_index % max(1, int(fps)) == 0:
            preview.image(annotated, caption=f"Frame {frame_index}",
                          use_container_width=True)
            progress.progress(min(.99, frame_index / max(1, limit)),
                              text=f"Frame {frame_index} of {limit}")
        frame_index += 1

    capture.release()
    writer.release()
    progress.progress(1.0, text="Complete")
    progress.empty()
    preview.empty()

    cols = st.columns(4)
    cards = [
        ("Unique potholes", str(unique_total), "crossed counting line", None),
        ("Large potholes", str(unique_large), "unique, severity Large",
         SEVERITY_HEX["large"] if unique_large else None),
        ("First detected", "—" if first_time is None else f"{first_time:.1f}s",
         "earliest detection", None),
        ("Frames written", str(frame_index), f"{fps:.0f} fps source", None),
    ]
    for col, (label, value, sub, colour), step in zip(cols, cards, range(1, 5)):
        col.markdown(metric_card(label, value, sub, colour, step), unsafe_allow_html=True)

    if output_path.is_file():
        st.video(str(output_path))
        st.download_button(
            "Download annotated video",
            output_path.read_bytes(),
            file_name=output_path.name,
            mime="video/mp4",
        )

    if counted:
        st.markdown("#### Counting log")
        st.dataframe(
            pd.DataFrame(counted, columns=["Track ID", "Crossed at (s)", "Severity"]),
            use_container_width=True, hide_index=True,
        )

    if rows:
        frame = pd.DataFrame(rows)
        st.download_button(
            "Download frame-level detections (CSV)",
            frame.to_csv(index=False).encode("utf-8"),
            file_name=f"video_detections_{uuid.uuid4().hex[:8]}.csv",
            mime="text/csv",
        )

    st.caption(
        "Unique counting uses IoU tracking plus line crossing to avoid recounting "
        "the same pothole across frames. It is an estimate — camera shake, "
        "occlusion or a static camera can affect it."
    )


# ======================================================================
# TAB 3 — BENCHMARK
# ======================================================================
def tab_benchmark() -> None:
    st.markdown("#### Test-set results — 198 held-out images, 433 labelled potholes")
    st.caption(
        "Model selection used the validation split; these figures come from the "
        "test split, evaluated once. P/R/F1 at confidence 0.50 and IoU 0.50."
    )

    frame = pd.DataFrame(BENCHMARK).T.reset_index().rename(columns={"index": "Model"})
    best = frame.loc[frame["mAP@0.5"].idxmax(), "Model"]

    cols = st.columns(4)
    winner = BENCHMARK[best]
    cards = [
        ("Best mAP@0.5", f"{winner['mAP@0.5']:.3f}", best, "#22C55E"),
        ("Best F1", f"{winner['F1']:.3f}", best, None),
        ("Fastest", f"{winner['FPS']:.0f} FPS", best, None),
        ("Smallest", f"{winner['Params (M)']:.1f}M", "parameters", None),
    ]
    for col, (label, value, sub, colour), step in zip(cols, cards, range(1, 5)):
        col.markdown(metric_card(label, value, sub, colour, step), unsafe_allow_html=True)

    st.markdown(
        f'<p style="margin-top:1rem;">Highest mAP@0.5: '
        f'<span class="pill pill-best">{best}</span></p>',
        unsafe_allow_html=True,
    )

    st.markdown("##### Accuracy metrics")
    st.bar_chart(
        frame.set_index("Model")[["mAP@0.5", "mAP@0.5:0.95", "Precision", "Recall", "F1"]],
        height=340,
    )

    st.markdown("##### Inference speed (FPS, higher is better)")
    st.bar_chart(frame.set_index("Model")[["FPS"]], height=260)

    st.markdown("##### Full results")
    st.dataframe(
        frame.style.format({
            "mAP@0.5": "{:.3f}", "mAP@0.5:0.95": "{:.3f}", "Precision": "{:.3f}",
            "Recall": "{:.3f}", "F1": "{:.3f}", "FPS": "{:.1f}", "Params (M)": "{:.1f}",
        }),
        use_container_width=True, hide_index=True,
    )

    with st.expander("Why confidence scores are not compared across models"):
        st.markdown(
            "YOLOv8 applies a **sigmoid** to its class logits, while SSD and "
            "Faster R-CNN apply a **softmax** over background-versus-pothole. "
            "The two scales are not calibrated to each other, so a higher raw "
            "confidence does not mean a more reliable detection.\n\n"
            "In these results Faster R-CNN reports the highest confidences yet "
            "has the **lowest precision** (0.697), while YOLOv8n reports lower "
            "confidences with the **highest precision** (0.891). Model quality "
            "is therefore judged on verified metrics, not raw confidence "
            "(Guo et al., 2017)."
        )


# ======================================================================
# MAIN
# ======================================================================
def main() -> None:
    inject_design_system()
    hero()
    cfg = sidebar()

    tab1, tab2, tab3 = st.tabs(["Image detection", "Video detection", "Benchmark"])
    with tab1:
        tab_image(cfg)
    with tab2:
        tab_video(cfg)
    with tab3:
        tab_benchmark()

    st.markdown(
        '<p style="text-align:center;color:#64748B;font-size:.78rem;'
        'margin-top:2.5rem;">Smart Road Pothole Detection System · '
        "BMCS2003 Artificial Intelligence · YOLOv8n · SSD300-VGG16 · "
        "Faster R-CNN ResNet50-FPN</p>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
